## H2 database application properties
## embedded used
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./provision/db/h2
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema-h2.sql
      data-locations: classpath*:db/data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true