## H2 database application properties
## embedded used
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema-h2.sql
      data-locations: classpath*:db/data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true